### ISSUE TITLE
Error running django compress

### ISSUE THREAD

**Issue by kesara** [ietf-tools/wagtail_website#256]
On staging envrioment, I get the following error when I run `./manage.py compress`:
```
./manage.py compress
Compressing... Traceback (most recent call last):
  File "/app/./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.10/site-packages/compressor/management/commands/compress.py", line 296, in handle
    self.handle_inner(**options)
  File "/usr/local/lib/python3.10/site-packages/compressor/management/commands/compress.py", line 319, in handle_inner
    offline_manifest, block_count, results = self.compress(engine, extensions, verbosity, follow_links, log)
  File "/usr/local/lib/python3.10/site-packages/compressor/management/commands/compress.py", line 229, in compress
    raise OfflineGenerationError(
compressor.exceptions.OfflineGenerationError: No 'compress' template tags found in templates.Try running compress command with --follow-links and/or--extension=EXTENSIONS
```

**Comment by mgax** [comment]
`django-compressor` was removed in https://github.com/ietf-tools/www/pull/350 so I'm guessing this issue is no longer relevant.
